### PR TITLE
add --hideLocal options

### PR DESCRIPTION
**Pull request by syarul**
Hello @skratchdot, great tools!, which I use very often. Btw I add new options which allow to hide local dep if it has same version as requested, it's limited to proceeding's symbols `<>=~^`. Test build on my fork succeeded [Build Status](https://travis-ci.org/syarul/npm-dview)

### CODE REVIEW

**Comment by skratchdot** [comment]
Thanks for doing this!  I'll pull it in now, but don't want to publish until I do a couple tests locally.  I'll try to get to it later today.

**Comment by skratchdot** [comment]
hey @syarul - just now getting around to testing this.  Can you describe your intended difference between:

`--excludeCurrent     Exclude up-to-date packages from the output`

and the feature you added:

`--hideLocal          Hide dependencies which local copy same as requestedVersion`

?

**Comment by skratchdot** [comment]
@syarul - I had to revert your commits in https://github.com/skratchdot/npm-dview/commit/d984069c4028e5d0fc5209ecd95c9e748d133283

only because I'm not seeing the intended difference between `excludeCurrent` and `hideLocal`, and when I ran both on an up-to-date package.json file, `hideLocal` displayed "undefined" in 2 places (instead of a nicely formatted table).

I'll re-accept a pull request though if I'm missing something.

I really appreciate the time and effort you took (but didn't want the chance for "undefined" to show up in my output)...

**Comment by syarul** [comment]
I'm aware of that, the `excludeCurrent` hide only up-to-date packages but not local copy which same as requested version. So with `hideLocal` it purposely remove "Javascript Fatigue" from the need to update every packages.Anyway, I'll make a PR once I got time on it

**Comment by skratchdot** [comment]
@syarul - I'll add it back in then.  There's was a case where it displayed "undefined", but I'll look into that. Thanks again...

**Comment by skratchdot** [comment]
I just published version 2.0.2 with your changes.  Can you install and check it out?

**Comment by skratchdot** [comment]
(I also added a link to your profile in the readme)

**Comment by syarul** [comment]
Ok, I' check it out.

**Pull request merged**
